# Generated by Django 5.1.7 on 2025-04-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='signatures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.CharField(default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SignatureComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_image', models.ImageField(upload_to='signatures/')),
                ('original_image', models.ImageField(upload_to='signatures/')),
                ('forged_image', models.ImageField(upload_to='signatures/')),
                ('orig_similarity', models.FloatField()),
                ('forg_similarity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
